
listedURL = {
    'Botkyrka': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17885',
    'Danderyd': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17892',
    'Ekerö': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17896',
    'Haninge': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17928',
    'Huddinge': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17936',
    'Järfälla': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17951',
    'Lidingö': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17846',
    'Nacka': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17853',
    'Norrtälje': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18003',
    'Nykvarn': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17855',
    'Nynäshamn': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18006',
    'Österåker': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17769',
    'Salem': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18019',
    'Sigtuna': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18020',
    'Södertälje': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17775',
    'Sollentuna': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18027',
    'Solna': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18028',
    'Stockholm': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18031',
    'Sundbyberg': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18042',
    'Täby': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17793',
    'Tyresö': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17792',
    'Upplands-Väsby': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17798',
    'Upplands-Bro': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17799',
    'Vallentuna': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17804',
    'Värmdö': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17818',
    'Vaxholm': 'https://www.hemnet.se/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17808',
}


soldURL = {
    'Botkyrka': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17885',
    'Danderyd': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17892',
    'Ekerö': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17896',
    'Haninge': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17928',
    'Huddinge': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17936',
    'Järfälla': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17951',
    'Lidingö': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17846',
    'Nacka': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17853',
    'Norrtälje': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18003',
    'Nykvarn': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17855',
    'Nynäshamn': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18006',
    'Österåker': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17769',
    'Salem': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18019',
    'Sigtuna': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18020',
    'Södertälje': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17775',
    'Sollentuna': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18027',
    'Solna': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18028',
    'Stockholm': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18031',
    'Sundbyberg': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=18042',
    'Täby': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17793',
    'Tyresö': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17792',
    'Upplands-Väsby': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17798',
    'Upplands-Bro': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17799',
    'Vallentuna': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17804',
    'Värmdö': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17818',
    'Vaxholm': 'https://www.hemnet.se/salda/bostader?item_types%5B%5D=bostadsratt&location_ids%5B%5D=17808',
}
